{% set name = "hdtconnector" %}
package:
  name: {{ name | lower }}
  version: {{ GIT_DESCRIBE_TAG }}
build:
  number: {{ GIT_DESCRIBE_NUMBER }}
  script_env:
    - CC
    - CXX
source:
  git_url: ../
requirements:
  build:
    - python
    - setuptools
    - hdtcpp
    - boost
  run:
    - python
    - hdtcpp
    - boost
test:
  source_files:
    - etc
    - hdtconnector/tests
  requires:
    - pytest
  commands:
    - pytest
about:
  home: https://github.com/ptorrestr/hdtconnector
  license: GPLv3
